package com.mercy.happybaby.entities;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.j256.ormlite.field.DatabaseField;

public class ActiveOperation implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -1961741578241447195L;
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int id;

	@DatabaseField
	String activeName;

	@DatabaseField
	int type;

	@DatabaseField(canBeNull = false)
	Date createdDate;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getActiveName() {
		return activeName;
	}

	public void setActiveName(String activeName) {
		this.activeName = activeName;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
