package com.mercy.happybaby.entities;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.j256.ormlite.field.DatabaseField;

public class Growth implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3590000596537873372L;
	/**
	 * 
	 */

	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int id;

	@DatabaseField(canBeNull = false)
	Date createdDate;

	@DatabaseField(canBeNull = true)
	float height;

	@DatabaseField(canBeNull = true)
	float weight;

	@DatabaseField(canBeNull = true)
	float headCirc;

	@DatabaseField(canBeNull = true)
	int month;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public float getHeight() {
		return height;
	}

	public void setHeight(float height) {
		this.height = height;
	}

	public float getWeight() {
		return weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	public float getHeadCirc() {
		return headCirc;
	}

	public void setHeadCirc(float headCirc) {
		this.headCirc = headCirc;
	}

	public int getMonth() {
		return month;
	}

	public void setMonth(int month) {
		this.month = month;
	}

}
