package com.mercy.happybaby.entities;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.j256.ormlite.field.DatabaseField;

public class Purchase implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -1961741578241447195L;
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField
	String purchaseName;

	@DatabaseField
	int purchasePrice;

	@DatabaseField
	int purchaseAmount;

	@DatabaseField(canBeNull = false)
	Date createdDate;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPurchaseName() {
		return purchaseName;
	}

	public void setPurchaseName(String purchaseName) {
		this.purchaseName = purchaseName;
	}

	public int getPurchasePrice() {
		return purchasePrice;
	}

	public void setPurchasePrice(int purchasePrice) {
		this.purchasePrice = purchasePrice;
	}
	
	

	public int getPurchaseAmount() {
		return purchaseAmount;
	}

	public void setPurchaseAmount(int purchaseAmount) {
		this.purchaseAmount = purchaseAmount;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
