package com.apu.maamuu.entities;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.j256.ormlite.field.DatabaseField;

public class Growth implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3590000596537873372L;
	/**
	 * 
	 */
	
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int id;
	
	@DatabaseField(canBeNull = false)
	Date createdDate;
	
	@DatabaseField
	int babyMonth;

	@DatabaseField
	int babyHeight;
	
	@DatabaseField
	int babyWeight;
	
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public int getBabyMonth() {
		return babyMonth;
	}

	public void setBabyMonth(int babyMonth) {
		this.babyMonth = babyMonth;
	}

	public int getBabyHeight() {
		return babyHeight;
	}

	public void setBabyHeight(int babyHeight) {
		this.babyHeight = babyHeight;
	}

	public int getBabyWeight() {
		return babyWeight;
	}

	public void setBabyWeight(int babyWeight) {
		this.babyWeight = babyWeight;
	}

	
}
