package com.apu.maamuu.entities;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.j256.ormlite.field.DatabaseField;

public class HelpCenter implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -1961741578241447195L;
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField
	String helpCenterTitle;

	@DatabaseField
	String helpCenterContent;

	@DatabaseField(canBeNull = false)
	Date createdDate;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getHelpCenterTitle() {
		return helpCenterTitle;
	}

	public void setHelpCenterTitle(String helpCenterTitle) {
		this.helpCenterTitle = helpCenterTitle;
	}

	public String getHelpCenterContent() {
		return helpCenterContent;
	}

	public void setHelpCenterContent(String helpCenterContent) {
		this.helpCenterContent = helpCenterContent;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
